Repository pasqal-io/qadence2-platforms, pull requests merged in 2024-12, with the labels that each got.

#35 Fixing coverage uploading issue
  .github/workflows/test.yml
  pyproject.toml
Labels: bug, infra

#40 Add piecewise backend function
  qadence2_platforms/backends/_base_analog/sequence.py
  qadence2_platforms/backends/analog/functions.py
  qadence2_platforms/backends/analog/sequence.py
Labels: feature

#49 Change name in confirm deployment step in ci/cd
  .github/workflows/test.yml
Labels: infra
